// <auto-generated />
namespace ModernStore.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v1Database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1Database));
        
        string IMigrationMetadata.Id
        {
            get { return "202008092121467_v1-Database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
